POST https://forum-api.dicoding.dev/v1/login
Content-Type: application/json

{
    "email" : "yoviarpauzi99@gmail.com",
    "password": "14112002"
}

###
POST https://forum-api.dicoding.dev/v1/register
Content-Type: application/json

{
    "name" : "yoii",
    "email": "test_1@gmail.com",
    "password" : "14112002"
}

###
GET https://forum-api.dicoding.dev/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXItNnNITjVxU3VjRERKcnowMiIsImlhdCI6MTcxNDU5MzMzOH0.Tofrvs_LuXERkCwL7BZpYaMGBrYqpnZRjapx3FMfjCQ